### ISSUE TITLE
Requerimientos funcionales

### ISSUE THREAD

**Issue by Angiemosquera** [Angiemosquera/Software-Magic-clothes#1]
Actividad:

Realizar los requerimientos funcionales de el software Magic Clothes, en documento de word y subirlo al repositorio.

**Comment by Agc1193** [comment]
Adjunto  los requerimientos  funcionales
[REQUERIMIENTOS FUNCIONALES.docx](https://github.com/Angiemosquera/Software-Magic-clothes/files/3102038/REQUERIMIENTOS.FUNCIONALES.docx)
[REQUERIMIENTOS FUNCIONALES.docx](https://github.com/Angiemosquera/Software-Magic-clothes/files/3102039/REQUERIMIENTOS.FUNCIONALES.docx)

**Comment by Angiemosquera** [comment]
El documento se encuentra en validacion

**Comment by Angiemosquera** [comment]
Buenas tardes Andrea,

Debes ser un poco mas especifica en los requerimientos,

te adjunto un ejemplo para que lo compares

Entre los posibles requerimientos funcionales de un sistema, se incluyen: 

Descripciones de los datos a ser ingresados en el sistema.
Descripciones de las operaciones a ser realizadas por cada pantalla.
Descripción de los flujos de trabajo realizados por el sistema.
Descripción de los reportes del sistema y otras salidas.
Definición de quien puede ingresar datos en el sistema.
Como el sistema cumplirá los reglamentos y regulaciones de sector o generales que le sean aplicables.



Ejemplos de requerimientos funcionales de proceso o área de negocio

El sistema enviará un correo electrónico cuando se registre alguna de las siguientes transacciones: pedido de venta de cliente, despacho de mercancía al cliente, emisión de factura a cliente y registro de pago de cliente.
Se permitirá el registro de pedidos de compra con datos obligatorios incompletos, los cuales podrán completarse posteriormente modificando el pedido. Antes de poder aprobarse los datos del pedido deben estar completos.
Al aprobar un pedido, la solicitud pasará al siguiente paso del flujo de trabajo (workflow) de aprobación configurado en el sistema.
El sistema permitirá a los usuarios autorizados el ingresar planes y cronogramas de proyecto.
El sistema permitirá aprobar, cambiar o actualizar planes y cronogramas de proyecto.
El sistema permitirá el envío automatizado de cartas de entrega de órdenes directamente al almacén.
A cada orden se le asignará un identificador único, que será utilizado para identificarla en todos los procesos subsecuentes que se realicen sobre esta.
Al ingresar ordenes de entrega, toda orden de entrega estará asociada a un pedido de venta.
La facturación de pedidos de venta se realizara en lotes, por medio de una pantalla de pedidos pendientes de facturación, la cual mostrará los pedidos no facturados. Una vez facturados los pedidos no se mostrarán en esta lista.
El sistema también permitirá el registro de facturas manuales no asociadas a pedidos, sin embargo, estas requerirán autorización por parte del grupo de Gerentes antes de ser contabilizadas.
El proceso de compras en el sistema abarcará los siguientes pasos y transacciones: Ingreso de la requisición, emisión de la solicitud de cotización y emisión de la orden de compra.


COMPÁRALOS VRS LO QUE TIENES Y LOS MODIFICAS DE ACUERDO A LO QUE HABLAMOS DE LOS QUE VA HACER EL INVENTARIO DE LA TIENDA  magic clothes.

**Comment by Agc1193** [comment]
[formato-ieee-830.docx](https://github.com/Angiemosquera/Software-Magic-clothes/files/3129916/formato-ieee-830.docx)
Hola  kathe adjuntos el formato  incluyendo los requerimientos funcionales modificados.

**Comment by Angiemosquera** [comment]
Buen dia,

Se reabre Issue.

**Comment by Angiemosquera** [comment]
se reabre
