### ISSUE TITLE
Historias de usuario

### ISSUE THREAD

**Issue by Angiemosquera** [Angiemosquera/Software-Magic-clothes#3]
Actividad

Realizar  todo el proceso y la documentación de las historias de usuario  basadas en el proyecto del inventario de la tienda  Magic Clothes.

Realizarlo en un documento de word

**Comment by caro-fonseca** [comment]
[Historias de usuario.xlsx](https://github.com/Angiemosquera/Software-Magic-clothes/files/3154876/Historias.de.usuario.xlsx)
