### ISSUE TITLE
Casos de Uso-Casos  de prueba

### ISSUE THREAD

**Issue by Angiemosquera** [Angiemosquera/Software-Magic-clothes#5]
Se debe realizar la documentación de los casos de uso y los de prueba  para el software Magic clothes.

**Comment by Angiemosquera** [comment]
[Casos de Uso Magic Clothes -  CS003- Crear Graficos.pdf](https://github.com/Angiemosquera/Software-Magic-clothes/files/3125728/Casos.de.Uso.Magic.Clothes.-.CS003-.Crear.Graficos.pdf)
[Casos de uso inventario.pdf](https://github.com/Angiemosquera/Software-Magic-clothes/files/3125729/Casos.de.uso.inventario.pdf)

**Comment by Angiemosquera** [comment]
> [Casos de Uso Magic Clothes - CS003- Crear Graficos.pdf](https://github.com/Angiemosquera/Software-Magic-clothes/files/3125728/Casos.de.Uso.Magic.Clothes.-.CS003-.Crear.Graficos.pdf)
> [Casos de uso inventario.pdf](https://github.com/Angiemosquera/Software-Magic-clothes/files/3125729/Casos.de.uso.inventario.pdf)

**Comment by Angiemosquera** [comment]
[Casos de Uso Magic Clothes (1).xlsx](https://github.com/Angiemosquera/Software-Magic-clothes/files/3164511/Casos.de.Uso.Magic.Clothes.1.xlsx)

**Comment by Agc1193** [comment]
Buena noche adjunto casos de uso
[casos de uso.pdf](https://github.com/Angiemosquera/Software-Magic-clothes/files/3225500/casos.de.uso.pdf)
