### ISSUE TITLE
Diagrama de secuencia

### ISSUE THREAD

**Issue by Angiemosquera** [Angiemosquera/Software-Magic-clothes#7]
Realizar la creacion de  los diagrama de secuencia, de acuerdo a los casos de uso, se debe realizar utilizando visual paradigm o Bizagi  lo puede descargar ingresando al siguiente Link: https://www.bizagi.com/es

**Comment by Angiemosquera** [comment]
Buenas Noches,
Adjunto y envio el diagrama de secuencia del caso de prueba (Generar Informes)
[diagrama Generar Informes_.pdf](https://github.com/Angiemosquera/Software-Magic-clothes/files/3219947/diagrama.Generar.Informes_.pdf)

**Comment by Agc1193** [comment]
Buena  noche adjunto diagrama de secuencia (favoritos)
[diagrama de secuencia favoritos.pdf](https://github.com/Angiemosquera/Software-Magic-clothes/files/3225462/diagrama.de.secuencia.favoritos.pdf)

**Comment by johinawa02** [comment]
[diagrama.Administrador_ (2).docx](https://github.com/Angiemosquera/Software-Magic-clothes/files/3230075/diagrama.Administrador_.2.docx)

**Comment by johinawa02** [comment]
[Caso de Uso administrador.docx](https://github.com/Angiemosquera/Software-Magic-clothes/files/3230076/Caso.de.Uso.administrador.docx)

**Comment by johinawa02** [comment]
[Casos.de.Uso.Magic.Clothes.-.CS006-.Administrador.docx](https://github.com/Angiemosquera/Software-Magic-clothes/files/3230077/Casos.de.Uso.Magic.Clothes.-.CS006-.Administrador.docx)

**Comment by Angiemosquera** [comment]
se reabre.

**Comment by Angiemosquera** [comment]
se reabre issue.
