### ISSUE TITLE
casos de uso 

### ISSUE THREAD

**Issue by Agc1193** [Angiemosquera/Software-Magic-clothes#8]
[https://app.zenhub.com/files/179616553/e3bec4f4-4b4b-4cdf-9e35-425a76ceccb6/download](https://app.zenhub.com/files/179616553/e3bec4f4-4b4b-4cdf-9e35-425a76ceccb6/download)

**Comment by Agc1193** [comment]
casos  de uso

**Comment by Angiemosquera** [comment]
se reabre
